import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "prismjs/themes/prism-tomorrow.css";
import "./globals.css";
import Navbar from "./components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + " bg-base-100"}>
        <div className="bg-base-100">{children}</div>
        <div className="fixed bottom-2 w-screen flex justify-center">
          <Navbar />
        </div>
      </body>
    </html>
  );
}
